from typing import Protocol

class BaseView(Protocol):
    def show_info_message(self, title: str, message: str) -> None: ...
    def show_error_message(self, title: str, message: str) -> None: ...
    def show_warning_message(self, title: str, message: str) -> None: ...
    def show_loading_message(self, title: str, message: str) -> None: ...
    def hide_loading_message(self) -> None: ...
    def ask_export_path(self, default_name: str) -> str | None: ...