from src.app.env import APP_SQL_SERVER, APP_SQL_DATABASE, APP_SQL_USERNAME, APP_SQL_PASSWORD

# APP CONFIG
APP_SIZE = "700x400"
APP_TITLE = "Generador de Reportes CliniView"
APP_ID = "unab.generar_reportes_cliniview.v1"

APP_SQL_SERVER = APP_SQL_SERVER
APP_SQL_DATABASE = APP_SQL_DATABASE
APP_SQL_USERNAME = APP_SQL_USERNAME
APP_SQL_PASSWORD = APP_SQL_PASSWORD